app:
  name: 'L0'
  version: '1.0.0'
postgres:
  host: 'localhost'
  port: '5588'
  user: 'postgres'
  password: 'postgres'
  name: 'l0'
  schema: 'orders'
http:
  host: 'localhost'
  port: '8000'
kafka:
  bootstrap_servers: 'localhost:9092' 
  topic: 'orders'