app:
  name: 'L0'
  version: '1.0.0'
postgres:
  host: 'localhost'
  port: '5432'
  user: 'postgres'
  password: 'qwerty'
  name: 'l0'
  pg_driver : 'pq'
http:
  host: 'localhost'
  port: '8080'
kafka:
  bootstrap_servers: 'localhost:9092' 
  topic: 'main-topic' 